apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
      - name: payments-service
        image: payments-service-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5004
        env:
        - name: DB_NAME
          value: payments-db
        - name: DB_USER
          value: user
        - name: DB_PASSWORD
          value: password
        - name: DB_HOST
          value: postgres-payments
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: LoadBalancer